name: Compile Plugin
on: [push, workflow_dispatch] # Сборка запустится при сохранении файла или вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Берем код

      - name: Set up JDK 21 # Ставим Java (для плагинов 2026 года нужна 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven # Если нашел pom.xml, используй это
        if: hashFiles('**/pom.xml') != ''
        run: mvn clean package

      - name: Build with Gradle # Если нашел build.gradle, используй это
        if: hashFiles('**/build.gradle*', '**/build.gradle.kts') != ''
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Result # Сохраняем готовый файл
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Jar
          path: |
            target/*.jar
            build/libs/*.jar
